;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-buffer
        beginning-of-buffer
        easy-kill
        ess-smart-comma
        indent-for-tab-command
        kill-region
        markdown-enter-key
        prelude-move-beginning-of-line
        sh-assignment
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-hybrid-sexp
        undo-tree-visualize
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        smex
        sp-remove-active-pair-overlay
        ))
